FROM ccoupe/opencv-dlib-cuda 

WORKDIR /usr/local/lib/mlface/

RUN pip3 install websockets imutils rpyc

COPY mlface.py /usr/local/lib/mlface/
COPY mlface.sh /usr/local/lib/mlface/
COPY lib/Algo.py /usr/local/lib/mlface/lib/ 
COPY docker-mlface.sh /usr/local/lib/mlface

CMD ["/usr/local/lib/mlface/docker-mlface.sh"]
