FROM ccoupe/opencv-dlib-cuda

WORKDIR /usr/local/lib/mlface/

COPY requirements.txt requirements.txt

RUN pip3 install -r ./requirements.txt

COPY mlface.py /usr/local/lib/mlface/
COPY mlface.sh /usr/local/lib/mlface/
COPY lib/Algo.py /usr/local/lib/mlface/lib/ 
COPY docker-mlface.sh /usr/local/lib/mlface

#COPY known_faces/* /usr/local/lib/mlface/known_faces/

CMD ["/usr/local/lib/mlface/docker-mlface.sh"]
